sudo: required

language: go

go:
  - 1.7

services:
  - docker

after_success:
  - docker build -t "fedolin/calculator:latest" .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push fedolin/calculator

